### ISSUE TITLE
add unit tests 

### ISSUE THREAD

**Issue by TomMelt** [Cambridge-ICCS/FTorch-benchmarks#14]
Can we use an existing unit test library, such as, [pFUnit](https://github.com/Goddard-Fortran-Ecosystem/pFUnit) to add unit tests to our benchmarks?

This could replace my custom unit test:
https://github.com/Cambridge-ICCS/fortran-pytorch-lib-benchmark/blob/8c85bbab78a5719a91beb9ed51900894f7a66f8d/benchmarker_utils.f90#L7-L33

**Comment by jatkinson1000** [comment]
Closing as should get covered by https://github.com/Cambridge-ICCS/FTorch/issues/4 in the main FTorch repo.
