### ISSUE TITLE
remove old tests

### ISSUE THREAD

**Issue by TomMelt** [Cambridge-ICCS/FTorch-benchmarks#18]
@jatkinson1000 

Can we safely remove `benchmarker_forpy.f90` and `cg_drag_*.f90` files?

I think we just need to keep the `benchmarker_*.f90` files?

**Comment by jatkinson1000** [comment]
You'd need to amend the CMakeLists, and I think there is a slight difference between the former and latter.

The former contains the call through an interface exactly as it occurs in MiMA, whilst the latter is the core of this code to call only the net pulled out into one file.

**Comment by TomMelt** [comment]
After discussion with @jatkinson1000 , we have decided to keep them as they serve a different purpose. They are structured differently from the simplified benchmarks offering a different, realistic implementation of the `FTorch` library
