### ISSUE TITLE
Make a benchmark with a simple neural network

### ISSUE THREAD

**Issue by dorchard** [Cambridge-ICCS/FTorch-benchmarks#8]
Following the simple test in this PR:
https://github.com/Cambridge-ICCS/fortran-pytorch-lib-benchmark/pull/7
Next steps are to go from multiplying a tensor to putting in a simple NN and benchmarking with that.

**Comment by jatkinson1000** [comment]
Closing this as stale and now covered elsewhere in the main FTorch examples.
